-- CreateTable
CREATE TABLE "USUARIOS" (
    "CODUSU" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "EMAIL" TEXT NOT NULL,
    "SENHA" TEXT NOT NULL,
    "LOGADO" BOOLEAN NOT NULL
);

-- CreateTable
CREATE TABLE "Pessoa" (
    "CODPES" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "NOME" TEXT NOT NULL,
    "SOBRENOME" TEXT NOT NULL,
    "CPF" TEXT NOT NULL,
    "TELEFONE" TEXT NOT NULL,
    "CODEND" INTEGER NOT NULL
);

-- CreateTable
CREATE TABLE "Endereco" (
    "CODEND" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "CEP" TEXT NOT NULL,
    "ENDERECO" TEXT NOT NULL,
    "NUMERO" INTEGER NOT NULL,
    "BAIRRO" TEXT NOT NULL,
    "UF" TEXT NOT NULL,
    "ESTADO" TEXT NOT NULL,
    "COMPLEMENTO" TEXT NOT NULL,
    CONSTRAINT "Endereco_CODEND_fkey" FOREIGN KEY ("CODEND") REFERENCES "Pessoa" ("CODEND") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "Pessoa_CPF_key" ON "Pessoa"("CPF");

-- CreateIndex
CREATE UNIQUE INDEX "Pessoa_CODEND_key" ON "Pessoa"("CODEND");
