-- RedefineTables
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_ENDERECOS" (
    "CODEND" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "CEP" TEXT NOT NULL,
    "ENDERECO" TEXT NOT NULL,
    "NUMERO" INTEGER NOT NULL,
    "BAIRRO" TEXT NOT NULL,
    "UF" TEXT NOT NULL,
    "ESTADO" TEXT NOT NULL,
    "COMPLEMENTO" TEXT NOT NULL
);
INSERT INTO "new_ENDERECOS" ("BAIRRO", "CEP", "CODEND", "COMPLEMENTO", "ENDERECO", "ESTADO", "NUMERO", "UF") SELECT "BAIRRO", "CEP", "CODEND", "COMPLEMENTO", "ENDERECO", "ESTADO", "NUMERO", "UF" FROM "ENDERECOS";
DROP TABLE "ENDERECOS";
ALTER TABLE "new_ENDERECOS" RENAME TO "ENDERECOS";
CREATE TABLE "new_PESSOAS" (
    "CODPES" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "NOME" TEXT NOT NULL,
    "SOBRENOME" TEXT NOT NULL,
    "CPF" TEXT NOT NULL,
    "TELEFONE" TEXT NOT NULL,
    "CODEND" INTEGER NOT NULL,
    CONSTRAINT "PESSOAS_CODEND_fkey" FOREIGN KEY ("CODEND") REFERENCES "ENDERECOS" ("CODEND") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "new_PESSOAS" ("CODEND", "CODPES", "CPF", "NOME", "SOBRENOME", "TELEFONE") SELECT "CODEND", "CODPES", "CPF", "NOME", "SOBRENOME", "TELEFONE" FROM "PESSOAS";
DROP TABLE "PESSOAS";
ALTER TABLE "new_PESSOAS" RENAME TO "PESSOAS";
CREATE UNIQUE INDEX "PESSOAS_CPF_key" ON "PESSOAS"("CPF");
CREATE UNIQUE INDEX "PESSOAS_CODEND_key" ON "PESSOAS"("CODEND");
PRAGMA foreign_key_check;
PRAGMA foreign_keys=ON;
