-- RedefineTables
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_USUARIOS" (
    "CODUSU" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "EMAIL" TEXT NOT NULL,
    "SENHA" TEXT NOT NULL,
    "LOGADO" BOOLEAN DEFAULT false
);
INSERT INTO "new_USUARIOS" ("CODUSU", "EMAIL", "LOGADO", "SENHA") SELECT "CODUSU", "EMAIL", "LOGADO", "SENHA" FROM "USUARIOS";
DROP TABLE "USUARIOS";
ALTER TABLE "new_USUARIOS" RENAME TO "USUARIOS";
PRAGMA foreign_key_check;
PRAGMA foreign_keys=ON;
